# Admin credentials
ADMIN_EMAIL = "buvjapanesecultureclub@gmail.com"
ADMIN_PASSWORD = "secretsociety"

# Email configuration
GMAIL_USER = "buvjapanesecultureclub@gmail.com"
GMAIL_APP_PASSWORD = "qskc sfyi kihk ygbt"