# Admin credentials
ADMIN_EMAIL = "buvjapanesecultureclub@gmail.com"
ADMIN_PASSWORD = "secretsociety"

# Email config
GMAIL_USER = "buvjapanesecultureclub@gmail.com"
GMAIL_APP_PASSWORD = "qskc sfyi kihk ygbt"

# Google Sheets Service Account
# IMPORTANT: Replace all values below with your actual JSON credentials

[gcp_service_account]
type = "service_account"
project_id = "interview-scheduler-473907"
private_key_id = "eceee80d3f5a45652246ca81653c966f23d91cfa"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDSU/x6bc3/NDXm\nQOnXieLKyEnRhtd6vHecmmEvpcgEwsfjrBTQhSMTlq5VQRJVgj73K+zZoIahxE77\nrP3YuEim607Ao0DYOzvZIFQuli8Fguohar+HVE9DHgkEggYCLmvpLTbRLnkr8Ay2\n1Ed3gtk9XhutyU/kYx7MLEqyCIIyrUiiMI31FGascz+YFN1UXaHH4mQhTr34QhVH\nzNZGxd/xvEEfahZubo1rB6dCgWM7NqLookFiv1Bo+5e9LRf5d10zxDZyTMeu1UOS\n/ON2vq9N/I3QqbY/C7oXBAd5g065Flp5Yd5Aqm89hhJRy3cnd2zgyDxYilVoDiXk\nRq6+5CXRAgMBAAECggEAF0buOUpvst+/W1UxzAXZkKGr8cFflZjIEA/R06kgQs6f\nuqWvxAgIAsH5VzwVYFtCxq4Yz1kBrWOBbj8N9O8oMzj1hUJMCeI8VGJMjr9WQuDj\nMoGS4tJE12O6kcImEhW7IZo8Z9gh1ugBMDa8FhDoI++HVqth6R/DJ8t7FMr2Rc9O\nLk/kvonIQxSAy/bn4OPSA5gaP/FeUl+mwM2pGWB6vBG7EoZgeI/3zFFibiSfPbxr\nlPl0+6A9NqdpsiL560k+7/5twQi8/ayz6vTu4afZL04OSxoetCZfM5wFzq3baSso\nCrRCCNkxKlJ9OgfRsw/woaVOYmDGuOLYdPdu8Qn5sQKBgQD5AUgeGRrkjzIaCoXA\nbg015XfsdDR1XP+NVSmD69/TUqB64tlI4eBefIhXHKCpu7lUVXLS/My+mEcRAXRa\n7SJksG278s1OiaBUZPJx1j5IxTa7DIHG3FonDOQ4da6kVeexkmqpueyFzzqlMRwN\nfFYvdMmDRZNkQKsWF9RgxuzJrQKBgQDYPI8+HMJQEdy8EqJs2gq3OejwCHYmKrzu\npHF80ITXRTGeD55JOjrxeL6JYQgZ4MbIDIfZPEptJZG/ZhsSB/MNb1j1RoxtBjpZ\nU36trfVyY2LVOzqvGjqUfMHEHn2ojRf1CkA0u/6/56dRJ7Ua23ZiUg4KTPwykZtq\nuiHDT26ZNQKBgDwRxRYNtGEi8lE57J5JbkJsQwv11Jnjf3rW6pb6lhpiungqtYRR\niVEB9dod+9w2fzULEBI6DiKEldBSa4Fr53om3bITlte1d8okOCCiMJBZkyR4le4l\nRlJZV80PBrx6RNSfn7+mLJrzLRCg0kWmkxwLrnlOlYn/18YSpZdbJdBZAoGANtSU\nVeGg/ACrgh0Php57XR6YDFV48BCiO7kC9e1B4fwvqq63KkZTr+s4FUm/biBrB0r2\nH4WEMcz2+ht//cB6RwvW+MrczMBph0D+vDeCJ3FAHGWaadAyzngcAgjhQB4W1xG0\nWirZW/v3l0KET70ada/s03vV71Swng14hjfcCYkCgYEAxhUTjmMm4gKN13Za5M9M\nDRu5fwgmsjY8Q5zFDVkVTaBpfBCCbVjbNlb5clbt7s8stQgHedya+QLmnWS0uz2+\nKj3bIoInksY07IHquR98wy/X9Ed1W7BHIUety64YPhLf55Ci4FPSZR8gBC2t6ypQ\nwMQozhqhHeM15FjsXRNgjmk=\n-----END PRIVATE KEY-----\n"
client_email = "interview-scheduler@interview-scheduler-473907.iam.gserviceaccount.com"
client_id = "116304087028781513681"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/interview-scheduler%40interview-scheduler-473907.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

